nome = input('Digite seu nome completo: ')
print('Analisando seu nome')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
semEspaco = nome.replace(' ','')
print('Seu nome tem ao todo {} letras'.format(len(semEspaco)))
nome = nome.split(' ')
print('Seu primeirmo nome é {} e tem {} letras'.format(nome[0],len(nome[0])))
